stages:
  - test
  - deploy
  - release

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

pre-commit:
  stage: test
  needs: []
  image: musicscience37/pipenv:noble
  variables:
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry install
    - poetry run pre-commit run --all-files
  cache:
    - key:
        prefix: poetry-linux
        files:
          - poetry.lock
      paths:
        - .poetry-cache
  interruptible: true

spell check:
  stage: test
  needs: []
  image: node
  script:
    - npm install -g cspell
    - cspell lint
      "**/*.py"
      "**/*.txt"
      "**/*.md"
      "**/*.rst"
      "**/*.yaml"
      "**/*.yml"
      "**/*.json"
      "**/*.toml"
      "**/*.sh"
      "**/*.bash"
  interruptible: true

build document:
  stage: test
  needs: []
  image: musicscience37/pipenv:noble
  variables:
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry install
    - ./docs/update_apidoc.sh
    - poetry run sphinx-build -b html -W -q docs/source docs/build
  cache:
    - key:
        prefix: poetry-linux
        files:
          - poetry.lock
      paths:
        - .poetry-cache
  artifacts:
    paths:
      - docs/build
  interruptible: true

pages main:
  stage: deploy
  needs:
    - build document
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  image: alpine
  script:
    - mv docs/build public
  artifacts:
    paths:
      - public
  pages: true

pages release:
  stage: deploy
  needs:
    - build document
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
  image: alpine
  script:
    - mv docs/build public
  artifacts:
    paths:
      - public
  pages:
    path_prefix: $CI_COMMIT_TAG
    expire_in: never

publish-package:
  stage: deploy
  needs: []
  image: musicscience37/pipenv:noble
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
  script:
    - poetry build
    - poetry config pypi-token.pypi ${PYPI_TOKEN}
    - poetry publish

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  needs: []
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
  script:
    - echo "This is a release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: "$CI_COMMIT_TAG"
    description: "./docs/source/release_notes/${CI_COMMIT_TAG}.md"
